name: q_rate_dialog
version: 0.0.1
description: "q_rate_dialog"
publish_to: 'none'
homepage: https://github.com/quanptit/q_rate_dialog  # Optional but recommended

environment:
  sdk: ^3.5.4

dependencies:
  q_common_utils:
    path: ../q_common_utils
  q_theme:
    path: ../q_theme
  package_info_plus: any
  in_app_review: any
  flutter_rating_bar: any
  json_annotation: any
  url_launcher: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - packages/q_rate_dialog/imgs/ic_rate_dialog.png
